# Generated by Django 6.0 on 2026-09-27 17:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_student_convention_name_student_discount_type_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Réduction convention'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='exemption_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Motif de l'exonération"),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_exempt',
            field=models.BooleanField(default=False, verbose_name='Exonéré de paiement'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant de base'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Réglé / مؤدى'), ('partial', 'Partiel / أداء جزئي'), ('unpaid', 'Non réglé / غير مؤدى'), ('exempt', 'Exonéré / معفى من الأداء')], default='unpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveIntegerField(verbose_name='Mois (1-12)')),
                ('period_year', models.PositiveIntegerField(default=2026, verbose_name='Année')),
                ('reason', models.CharField(blank=True, default='Exonération accordée', max_length=255, verbose_name='Motif / Cause')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_exemptions', to='academy.student')),
            ],
            options={
                'verbose_name': 'Exonération de paiement',
                'verbose_name_plural': 'Exonérations de paiement',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('student', 'period_month', 'period_year')},
            },
        ),
    ]
