# Generated by Django 6.0 on 2026-09-06 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom (Français)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Nom (Arabe)')),
                ('icon', models.CharField(default='💸', max_length=20, verbose_name='Icône / Emoji')),
                ('color', models.CharField(default='#0284C7', max_length=20, verbose_name='Couleur Badge (Hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Libellé / Titre de la dépense')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (DH)')),
                ('expense_date', models.DateField(verbose_name='Date de la dépense')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces / نقداً'), ('check', 'Chèque / شيك'), ('transfer', 'Virement bancaire / تحويل بنكي')], default='cash', max_length=20, verbose_name='Mode de règlement')),
                ('beneficiary', models.CharField(blank=True, max_length=150, verbose_name='Bénéficiaire / Fournisseur')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='N° Facture / Référence')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='expenses/%Y/%m/', verbose_name='Justificatif (Scan / Reçu / Facture)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.expensecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-expense_date', '-id'],
            },
        ),
    ]
