# Generated by Django 6.0 on 2026-10-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_discount_amount_invoice_exemption_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='period_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mois concerné / الشهر المؤدى عنه (1-12)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='period_year',
            field=models.PositiveIntegerField(blank=True, default=2026, null=True, verbose_name='Année concernée / السنة'),
        ),
    ]
