# Generated by Django 6.0 on 2026-09-06 20:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expensecategory_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('month', 'Mensuelle / شهري'), ('year', 'Annuelle (Exercice) / سنوي')], default='month', max_length=20, verbose_name='Type de clôture')),
                ('year', models.IntegerField(verbose_name='Année / Exercice')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='Mois (1-12 si mensuel)')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre / Intitulé')),
                ('status', models.CharField(choices=[('draft', 'Brouillon / مسودة'), ('closed', 'Clôturé / مغلق'), ('approved', 'Approuvé par le Bureau / مصادق عليه')], default='draft', max_length=20, verbose_name='Statut')),
                ('closing_date', models.DateField(verbose_name='Date de clôture')),
                ('initial_cash_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Solde initial Caisse Espèces (DH)')),
                ('initial_bank_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Solde initial Compte Bancaire (DH)')),
                ('total_collected_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Recettes Espèces (DH)')),
                ('total_collected_bank', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Recettes Banque / Virements & Chèques (DH)')),
                ('total_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Recettes Encaissées (DH)')),
                ('total_expense_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Dépenses payées en Espèces (DH)')),
                ('total_expense_bank', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Dépenses payées par Banque (DH)')),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Dépenses & Charges (DH)')),
                ('net_result', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Résultat Net (Excédent / Déficit) (DH)')),
                ('theoretical_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Solde théorique Caisse Espèces (DH)')),
                ('theoretical_bank', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Solde théorique Compte Bancaire (DH)')),
                ('physical_cash_counted', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Comptage physique réel de Caisse (DH)')),
                ('bank_statement_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Solde relevé bancaire de fin de période (DH)')),
                ('cash_discrepancy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Écart de Caisse (Réel - Théorique) (DH)')),
                ('bank_discrepancy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Écart Bancaire (Relevé - Théorique) (DH)')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Période verrouillée (Gel des écritures)')),
                ('treasurer_notes', models.TextField(blank=True, verbose_name='Observations du Trésorier Général')),
                ('president_notes', models.TextField(blank=True, verbose_name='Observations du Président')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Clôturé par')),
            ],
            options={
                'verbose_name': 'Clôture financière',
                'verbose_name_plural': 'Clôtures financières',
                'ordering': ['-year', '-month', '-id'],
            },
        ),
    ]
