# Generated by Django 6.0 on 2026-09-06 22:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_trainer_sessionschedule_trainer'),
        ('finance', '0003_financialclosing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='N° Bulletin / Référence')),
                ('period_month', models.PositiveIntegerField(verbose_name='Mois')),
                ('period_year', models.PositiveIntegerField(default=2026, verbose_name='Année')),
                ('compensation_type', models.CharField(choices=[('monthly_fixed', 'Forfait mensuel fixe / مبلغ شهري قار'), ('per_session', 'Par séance dispensée / بالحصّة'), ('per_hour', 'Taux horaire / بالساعة')], default='per_session', max_length=20, verbose_name='Mode de calcul')),
                ('sessions_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de séances')),
                ('rate_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Taux / Tarif appliqué (DH)')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant de Base (DH)')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Primes & Indemnités (DH)')),
                ('bonus_description', models.CharField(blank=True, max_length=255, verbose_name='Motif de la prime')),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Retenues & Avances (DH)')),
                ('deduction_description', models.CharField(blank=True, max_length=255, verbose_name='Motif de la retenue')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Net à Payer (DH)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon / مسودة'), ('validated', 'Validé / مصادق عليه'), ('paid', 'Réglé / مؤدى')], default='draft', max_length=20, verbose_name='Statut')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces / نقداً'), ('transfer', 'Virement bancaire / تحويل بنكي'), ('check', 'Chèque / شيك')], default='cash', max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='N° Chèque / Virement')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_payout', to='finance.expense', verbose_name='Écriture de dépense associée')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='academy.trainer', verbose_name='Formateur')),
            ],
            options={
                'verbose_name': "Bulletin d'honoraires formateur",
                'verbose_name_plural': "Bulletins d'honoraires formateurs",
                'ordering': ['-period_year', '-period_month', '-id'],
                'unique_together': {('trainer', 'period_month', 'period_year')},
            },
        ),
    ]
