# Generated by Django 6.0 on 2026-10-02 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payment_period_month_payment_period_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate),
        ),
    ]
