# Generated by Django 6.0 on 2026-09-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_parentvisitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Adresse / Domicile'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Niveau de scolarité'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='École de scolarité'),
        ),
    ]
