# Generated by Django 6.0 on 2026-09-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_parent_address_student_grade_level_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Couleur du Groupe / لون المجموعة'),
        ),
    ]
