# Generated by Django 6.0 on 2026-09-06 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_group_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('cancel_all_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='academy.sessionschedule')),
            ],
            options={
                'verbose_name': 'Annulation de séance',
                'verbose_name_plural': 'Annulations de séances',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
