# Generated by Django 6.0 on 2026-09-11 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_sessioncancellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre / Objet')),
                ('content', models.TextField(verbose_name='Message / Contenu')),
                ('message_type', models.CharField(choices=[('info', 'Information générale / إشعار عام'), ('reminder', 'Rappel de séance / تذكير بالحصص'), ('pedagogy', 'Pédagogie & Devoirs / محتوى تربوي وتمارين'), ('event', 'Événement & Tournoi / حدث أو بطولة'), ('urgent', 'Urgent / عاجل')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_messages', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='academy.group')),
            ],
            options={
                'verbose_name': 'Message de Groupe',
                'verbose_name_plural': 'Messages de Groupe',
                'ordering': ['-created_at'],
            },
        ),
    ]
