# Generated by Django 6.0 on 2026-09-06 22:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_sessioncancellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_fr', models.CharField(max_length=100, verbose_name='Prénom (FR)')),
                ('last_name_fr', models.CharField(max_length=100, verbose_name='Nom (FR)')),
                ('first_name_ar', models.CharField(blank=True, max_length=100, verbose_name='الاسم الشخصي')),
                ('last_name_ar', models.CharField(blank=True, max_length=100, verbose_name='الاسم العائلي')),
                ('cin', models.CharField(blank=True, max_length=30, verbose_name="CIN (N° Carte d'identité)")),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('specialty', models.CharField(default='Échecs / الشطرنج', max_length=150, verbose_name='Discipline / Spécialité')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresse / Domicile')),
                ('compensation_type', models.CharField(choices=[('monthly_fixed', 'Forfait mensuel fixe / مبلغ شهري قار'), ('per_session', 'Par séance dispensée / بالحصّة'), ('per_hour', 'Taux horaire / بالساعة')], default='per_session', max_length=20, verbose_name='Mode de rémunération')),
                ('default_rate', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10, verbose_name='Tarif de base (DH)')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Nom de la Banque')),
                ('bank_rib', models.CharField(blank=True, max_length=50, verbose_name='RIB Bancaire (24 chiffres)')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
                'ordering': ['last_name_fr', 'first_name_fr'],
            },
        ),
        migrations.AddField(
            model_name='sessionschedule',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='academy.trainer', verbose_name='Formateur titulaire'),
        ),
    ]
