# Generated by Django 6.0 on 2026-09-27 17:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='convention_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nom de la convention / Organisme partenaire'),
        ),
        migrations.AddField(
            model_name='student',
            name='discount_type',
            field=models.CharField(choices=[('custom_fee', 'Tarif mensuel forfaitaire (DH) / سومة اتفاقية محددة'), ('fixed_discount', 'Réduction fixe en DH / تخفيض بقيمة محددة'), ('percentage', 'Pourcentage de réduction (%) / نسبة تخفيض مئوية')], default='custom_fee', max_length=20, verbose_name='Type de réduction'),
        ),
        migrations.AddField(
            model_name='student',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valeur de la réduction ou Tarif (DH ou %)'),
        ),
        migrations.AddField(
            model_name='student',
            name='has_convention',
            field=models.BooleanField(default=False, verbose_name="Bénéficie d'une convention / يستفيد من اتفاقية"),
        ),
    ]
